### ISSUE TITLE
Bugs in Clasp's reader

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#190]
There were several reader problems that some of Shinmera's code revealed.
For instance:

Both (read-from-string "#\/") and (list #+windows #\/) failed

Some of the Readtable_O functions had specific return types Character_sp and Function_sp but they returned NIL.  That caused a bad type failure.  I've switched them to return T_sp

**Comment by drmeister** [comment]
I fixed the problem with (list #+windows #\/) failing.   The af_sharp_backslash function was returning nothing ( Values0<T_O>() ) when it should have been returning NIL

**Comment by drmeister** [comment]
I found several other issues while looking through the reader code.  *preserve-whitespace-p* is handled better now.

**Comment by Shinmera** [comment]
`(list #+windows #\/)` confirmed fixed on 13212515bc40d3ef84bed8d2f4c8ce8ec3399af1.
`(read-from-string "#\/")` still fails with
```
Condition of type: SIMPLE-PROGRAM-ERROR
Undefined reader macro for #\# #\/
```

**Comment by Bike** [comment]
So... that fails because the escaping is applied by the string reader. Basically `(length "#\/")` => 2. I think I've been wondering about this for like a year but only now did i try it in SBCL and get the same result.
