### ISSUE TITLE
Several regressions after last array cleanups

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#867]
The following regression-tess now fail:
`(COPY-TO-SIMPLE-BASE-STRING0 COPY-TO-SIMPLE-BASE-STRING1
                     COPY-TO-SIMPLE-BASE-STRING2 COPY-TO-SIMPLE-BASE-STRING3
                     EQUALP-CLHS-2A EQUALP-7 PRINT-5)`

Looking at the copy-* the following no longer seem to work:
```lisp
COMMON-LISP-USER> (make-array 3 :element-type 'character :initial-element #\C)
""
````
The array is created, but the initial-value is not applied.
Looking at the code, 
(CORE:MAKE-VECTOR 'CHARACTER 3 NIL NIL NIL 0 #\C T) is called, than probably
SimpleBaseString_sp make than probably
gctools::GC<SimpleBaseString_O>::allocate_container_null_terminated_string

**Comment by Bike** [comment]
`core:make-simple-vector-base-char` still works. that doesn't make a ton of sense. And it's broken with `base-char` as well. Character strings just use `allocate_container` instead of `allocate_container_null_terminated_string` so maybe the problem isn't that deep.

**Comment by Bike** [comment]
Things are also messed up for other specialized types, e.g. `(core:make-vector 'ext:byte32 3 nil nil nil 0 32 t) => #(1 1 1)`. But `make-simple-vector-[whatever]` seems fine. What the fuck.

**Comment by kpoeck** [comment]
The string things are fixed, so now only 
* EQUALP-CLHS-2A
* EQUALP-7
* PRINT-5
fail

can describe that here, or open a new issue, as you prefer

**Comment by drmeister** [comment]
kpoeck: They look different - could you create a new issue.
I'm still seeing a hang when starting slime.
